AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  RoleName:
    Type: String
    Default: StaxLinkingManagement
    AllowedValues:
    - StaxLinkingManagement
    Description: The role name used for Stax control plane assertion

  StaxMasterAccountId:
    Type: String
    AllowedPattern: "^([0-9]){12}$"

Resources: 
  StaxLinkingManagement: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${StaxMasterAccountId}:root
            Action: sts:AssumeRole
      Path: /stax/
      Policies:
        - PolicyName: "stax-access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: "Allow"
              Action:
                - "iam:*"
                - "cloudformation:*"
              Resource: "*"

